### ISSUE TITLE
os.mkdir() will throw an exception on NTFS file systems if manga name breaks Windows naming convention

### ISSUE THREAD

**Issue by nekorug** [Hamuko/cum#22]
Example: `It's Not My Fault That My Friend's Not Popular.`
url: `https://bato.to/comic/_/comics/its-not-my-fault-that-my-friends-not-popular-r8377`

I'm running Arch Linux and Python 3.5.1. My download directory's file system is NTFS. I can manually create directories that end with a dot, but it won't work in Python. Python doesn't allow this as it conflicts with [the Windows naming conventions](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions), even if it's technically possible in NTFS:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not.

The fact that I do not get this error if my download directory's file system is ext4 supports this conclusion. 

I realize this is somewhat of an edge-case, but it would be neat if NTFS file systems where detected and the directory and file names where pruned to be acceptable according to Python. Specifically, this would entail stripping the directory and filename from these characters: `<>:"/\|?*` and `.` if it is the last character in a directory name (all filenames should end with .zip/.cbz by default, so they won't be an issue). 

I couldn't find any details on how one could detect if a file system was NTFS from Python, so an easier solution could be a new option: `windows_naming_convention` which defaults to `false`. 

Terminal output:

    $ cum get https://bato.to/comic/_/comics/its-not-my-fault-that-my-friends-not-popular-r8377
    its-not-my-fault-that-my-friends-not-popular 28
      [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  5/5  100%
    Traceback (most recent call last):
      File "/usr/bin/cum", line 9, in <module>
        load_entry_point('cum==0.4', 'console_scripts', 'cum')()
      File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/cum/cum.py", line 16, in wrapper
        return f(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/cum/cum.py", line 189, in get
        chapter.get(use_db=False)
      File "/usr/lib/python3.5/site-packages/cum/scrapers/base.py", line 208, in get
        self.download()
      File "/usr/lib/python3.5/site-packages/cum/scrapers/batoto.py", line 168, in download
        self.create_zip(files)
      File "/usr/lib/python3.5/site-packages/cum/scrapers/base.py", line 112, in create_zip
        with zipfile.ZipFile(self.filename, 'w') as z:
      File "/usr/lib/python3.5/site-packages/cum/scrapers/base.py", line 191, in filename
        os.makedirs(directory)
      File "/usr/lib/python3.5/os.py", line 241, in makedirs
        mkdir(name, mode)
    OSError: [Errno 22] Invalid argument: "/dl/It's Not My Fault That My Friend's Not Popular."

**Comment by Hamuko** [comment]
I'll take a look at what would be the most elegant solution to the issue.

**Comment by Hamuko** [comment]
I'm actually now leaning on just implementing a config option to prune those characters from directory names since I am unable to reproduce the bug using CentOS, Python 3.5.1 and an external NTFS drive mounted using NTFS-3G.

**Comment by nekorug** [comment]
That's strange. It might be possible that you'd need to mount it with the `windows_names` option, if that is how Python determines whether to adhere to the Windows naming convention. 

Here is the relevant part of my `/etc/fstab` (`/dl/` is symlinked to it):

    LABEL=media             /mnt/m          ntfs-3g defaults,relatime,windows_names,nofail,x-systemd.device-timeout=1

**Comment by Hamuko** [comment]
That sounds likely. I'll try it later with `windows_names` enabled. I just mounted my disk quite simply with `/dev/sda1 /mnt/usb ntfs-3g rw,umask=0000,defaults 0 0`.

**Comment by Hamuko** [comment]
Unsurprisingly enough, using the `windows_names` option does indeed result in the reported behavior.

I added a fallback directory name sanitization on 3b85bf79e962b911832047bc861fcd7313cebb9c which should automatically perform on error so please test it. However I am not entirely sure if I am happy with this implementation though, so I might or might not change it in the future.

**Comment by nekorug** [comment]
It works! 

Thanks for the fixing this, and thanks for creating the tool to begin with!
