### ISSUE TITLE
Unfollowing a series doesnt reset downloaded column

### ISSUE THREAD

**Issue by abduct** [Hamuko/cum#31]
I was attempting to force a redownload of a entire manga since it was downloaded with a previous version which had a filename bug in it from a prior commit.

When doing

```
cum unfollow trash
#delete the physical folder
cum follow https://bato.to/comic/_/comics/trash-r13308
cum update
cum download trash
```

the result was that 0 chapters have been downloaded. Specifying the --download flag for the follow command did not change this result.

My solution: Manually edit the cum.db database to set your series downloaded flag back to zero and then re-run the download command.

If I recall my query I ran was something like:

`UPDATE chapters SET downloaded = 0 where series_id = (select id from series where alias = "trash");`

Possible solutions may be to set the downloaded flag to 0 after an unfollow has occured (or remove it completely from the database) and/or add a --force-download flag to some of the commands.

**Comment by Hamuko** [comment]
Intended behavior so you can unfollow a series that dies (as they do with scanlations) and refollow it without losing your download info. `cum get` ignores the downloaded status.

**Comment by abduct** [comment]
I see. The get command still lacks the redownloading of an entire series. Is there a wild card avaliable to fetch all chapters? Running 

`cum get trash`

Does not yeild any results other than 'invalid selection "trash"'

**Comment by Hamuko** [comment]
I should probably add that for the next version.

**Comment by CounterPillow** [comment]
Running `cum get` on the series URL instead of on the alias should download the entire thing. Would be nice if running it on the alias worked too, though.

**Comment by Hamuko** [comment]
I added the ability to use `cum get` with aliases in the _get-alias_ branch. I'll merge it soon to master unless any issues come up.
