### ISSUE TITLE
MangaFox scraping support

### ISSUE THREAD

**Issue by abduct** [Hamuko/cum#34]
Hi, I am wondering if support for Mangafox scraping will be added to Cum. There are a few mangas that Batoto removed the English versions of which Mangafox has.

Thanks.

**Comment by Hamuko** [comment]
Isn't everything on Mangafox downscaled and watermarked? Doesn't sound like worth any effort.

**Comment by abduct** [comment]
It is watermarked, I am not sure about downscaled.

Although I think more sources would be nice. I have only been able to find "Online - The comic" on MangaFox so far. I haven't checked your other sources as of yet.

**Comment by Hamuko** [comment]
As far as I can see, Mangafox takes chapters, downscales them, adds a watermark and then saves them as low-quality JPG even if the source is PNG.

For comparison: [Mangafox](https://0x0.st/mnE.jpg) (728x1127 with watermark) vs. [Batoto](https://0x0.st/mn6.png) (909x1300).

Again, seems like a complete waste of time of a site. I imagine it has no content that is not available somewhere else already.

**Comment by abduct** [comment]
I've searched all supported sources and the manga I referenced to is not found in English on any of them.

It's up to you to add it as a source, more source the better at least to me, it's not like people are forced to use it if there is a source with better quality.

I used my personal scaper I wrote to fetch the manga, but seeing another source added to cum would be nice on top of the ones already present.

**Comment by Hamuko** [comment]
>I've searched all supported sources and the manga I referenced to is not found in English on any of them.

You mean [this manga](https://manga.madokami.al/Manga/O/ON/ONLI/Online)?

**Comment by abduct** [comment]
I can't tell. How do you sign up for that source. Their root domain http://madokami.al/ gives me a connection reset, and I can't find a register page.

**Comment by Hamuko** [comment]
HTTPS only. Details on the site.

Anyways, Mangafox seems like a waste of my time since I am the one who has to write and maintain it.

**Comment by CounterPillow** [comment]
Details aren't on the site anymore it seems. (The domain should be https://manga.madokami.al)

Join #madokami on irc.rizon.net and read the topic, instructions should be there.
