### ISSUE TITLE
Malformed names from source site causes overwritten archives

### ISSUE THREAD

**Issue by abduct** [Hamuko/cum#35]
Specific Mangas such as https://bato.to/comic/_/comics/homunculus-r1543 have malformed names in which all chapters are released under the name "ch.0". This was because this series had no chapter breaks so scanlators released them per volume rather than per chapter.

This causes Cum to overwrite the same archive each download since it is parsing the metadata for only chapters and not volumes and chapters.

For instance the filename for ALL Illuminati-Manga releases is Homunculus - c000 [Illuminati-Manga].zip and causes each volume downloaded under this groups name to overwrite itself.

Madokami source works a bit better, as in it downloads all the volumes since they have the volumes postfixed to the chapter number, but still requires manual renaming due to bad naming conventions.

Bato.to source can be fixed by appending the volume specified to the file name, not sure how to fix madokami easily.

**Comment by Hamuko** [comment]
I'm not completely sure what I should do about the issue. The sites have usually been a bit of a clusterfuck as how to and when they use volume numbering so I've been adverse to adding it. I probably need to think about how to implement it if I'll add them.

**Comment by CounterPillow** [comment]
I suggest a short-term solution would be to avoid overwriting files and simply increasing a counter in the filename on name conflicts, until we can find a better solution. This would at least avoid people having to download things manually.

This issue affects multiple scrapers, I've also seen this happen on Dynasty-Scans before where specials were grouped as their own chapters in a "Specials" volume.

**Comment by CounterPillow** [comment]
Looking at how we can solve the situation for [Lily Love](http://dynasty-scans.com/series/lily_love) on DS, I'm wondering how the naming of the archives should go.

The specials don't have a clearly associated parent chapter (e.g. 10.5), but are stand-alone mini chapters of their own. According to the manga naming scheme, I think the best solution would be to treat them as oneshots them, e.g. "Lily Love - 000 x1 [Special]".

As for Homunculus, the numbering on Batoto is a complete clusterfuck and pretty much incompatible with Daiz' manga naming scheme. Either we break the scheme, or we try to fetch supplemental information from some third party source about how many chapters there are in any given volume. I can see that at least MAL knows how many chapters and volumes there are in total, and once we know how many chapters there are in each volume, we can conform to our cozy manga naming scheme again.

Ideally Batoto would just fix their shit though.

**Comment by Hamuko** [comment]
>I suggest a short-term solution would be to avoid overwriting files and simply increasing a counter in the filename on name conflicts, until we can find a better solution.

I've implemented this (hopefully) short-term solution and it's currently up on master. I might later make a meta-issue to track progress of adding volume tracking to all the current scrapers. But in the meanwhile, I'll close this issue since I consider it "fixed" as of now.
