### ISSUE TITLE
NotADirectoryError under Windows 

### ISSUE THREAD

**Issue by SchubmannM** [Hamuko/cum#39]
I know you can manually change the directory that cum is downloading the chapters into, but thought I would still report this.
When there are manga that have special characters in their name (e.g "Boruto: Naruto Next Generations"), a NotADirectoryError is thrown as Windows does not allow folder names to have special characters.

**Comment by Hamuko** [comment]
Fixed on master.

**Comment by SchubmannM** [comment]
Any chance to update the pip package as well?

**Comment by CounterPillow** [comment]
Once there's a released and tagged version, the pip package will be upgraded. If you want the git master right now, use

```pip install git+https://github.com/Hamuko/cum```
