### ISSUE TITLE
Error following a raw in Madokami

### ISSUE THREAD

**Issue by DonRyuDragoni** [Hamuko/cum#49]
```
$ cum --version
cum version git-4405206 "Miyamo Chio-chan"
```

Hello. The title is pretty self-explanatory, so let me get right into the error:

```
$ cum follow 'https://manga.madokami.al/Raws/Yotsubato%21'
==> Invalid URL "https://manga.madokami.al/Raws/Yotsubato%21"
```

That URL, however, [is valid][]. Is this behaviour intentional? By that, I mean, are you intentionally blocking raws? ([From here][] it looks like that you're checking `/Manga/*` only, but nowhere in this repository I found something about raws, hence my question.)

[is valid]: https://manga.madokami.al/Raws/Yotsubato%21
[from here]: https://github.com/Hamuko/cum/blob/master/cum/scrapers/madokami.py#L14

**Comment by Hamuko** [comment]
Added the Raws path to the regex. I imagine it's useless though, since the filenames are all over the place. Maybe in the future Madokami will actually become a manga site and we can actually scrape it.
