### ISSUE TITLE
Madokami site revamp

### ISSUE THREAD

**Issue by phantom-voltage** [Hamuko/cum#6]
Madokami recently switched servers and the site layout has changed. The series overview is no longer accessible, manga.madokami.com redirects to the main page. The ftp folders are visible, but they do not seem to work when using cum follow.

**Comment by Hamuko** [comment]
I'm not noticing this manga.madokami.com redirect nor the new layout. And I've actually been able to download a few chapters from there after the server switch happened.

**Comment by phantom-voltage** [comment]
Hmm, ok, I'll try to poke around the site and see what I'm missing. Sorry about that, just haven't been able to add new series. I might need to delete my browser cache.
